version: 1

project:
  root: .
  build_config: lzc-build.yml
  package_file: package.yml
  output: .lazycat-build/diarum.lpk
  target_arch: amd64

update:
  strategy: publish
  allow_downgrade: false
  version_source:
    type: image
    image: diarum
build:
  run_buildscript: false
images:
  - id: diarum
    target: service
    service: diarum
    source: songtianlun/diarum
    channel: stable
    sort: semver
    tag_regex: '^v?\d+\.\d+\.\d+$'
    delivery:
      mode: mirror
stores:
  official:
    enabled: false
    skip_if_version_exists: true
  private:
    enabled: true
    skip_if_version_exists: true
    name: Diarum
    summary: "一款零负担、快记录、宜复盘的日记应用"
