application:
  subdomain: diarum
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://diarum:8090/
services:
  diarum:
    # upstream: songtianlun/diarum:v0.8.8
    image: docker.1ms.run/songtianlun/diarum:v0.8.8
    environment:
      - DIARUM_DATA_PATH=/app/data
    binds:
      - /lzcapp/var/data:/app/data
    cpu_shares: 512
    mem_limit: 512M
